apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wikijs-web
  namespace: {{ .Values.namespace }}
  labels:
    name: wikijs-web
spec:
  rules:
    - host: {{ .Values.ingress.web }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wikijs
                port:
                  number: 80