apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wikijs-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: wikijs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.storage.size}}
  storageClassName: {{.Values.storage.class_name}}