apiVersion: apps/v1
kind: Deployment
metadata:
  name: wikijs
  namespace: {{.Values.namespace}}
spec:
  selector:
    matchLabels:
      app: wikijs
  replicas: {{.Values.replicas}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wikijs
    spec:
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /wiki/data"]
        volumeMounts:
        - name: wikijs-pvc
          mountPath: /wiki/data
      containers:
        - name: wikijs
          image: requarks/wiki:latest
          workingDir: /wiki
          ports:
            - name: wikijs-web
              protocol: TCP
              containerPort: 3000
          env:
            - name: DB_TYPE
              value: "postgres"
            - name: DB_HOST
              value: "postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: wikijs_db_password
            - name: DB_NAME
              value: "postgres"
          volumeMounts:
            - name: wikijs-pvc
              mountPath: "/wiki/data"
      volumes:
        - name: wikijs-pvc
          persistentVolumeClaim:
            claimName: wikijs-pvc