apiVersion: v1
kind: Service
metadata:
  name: wikijs-web
  namespace: {{.Values.namespace}}
  labels:
    app: wikijs
spec:
  selector:
    app: wikijs
  ports:
  - name: wikijs-web
    port: 80
    targetPort: 3000
    nodePort: 30380
  type: NodePort